### ISSUE TITLE
フォルダー設定で楽曲情報データベースの無効化ができるように

### ISSUE THREAD

**Issue by shinta0806** [shinta0806/YukaListerNebula#76]
フォルダー内にあるファイルの情報がほとんど楽曲情報データベースに登録されていない場合は、楽曲情報データベースを参照するよりもファイル命名規則の情報をそのまま使う方がリストの精度があがる場合があります。

フォルダーごとに、楽曲情報データベースを使用するかしないか選べるようにして欲しいです。

［対応状況］検討中
［報告経路］コンタクト

**Comment by shinta0806** [comment]
（メモ）
実例を確認中。

**Comment by shinta0806** [comment]
（メモ）
同名の他の曲・タイアップがあって正しく分類されないケースで無効化したいとのことだが、その場合、正しく分類されている他の多くのファイルに悪影響が出るので、トータルでは無効化するほうが悪化する可能性が高い。同名の曲・タイアップを楽曲情報データベースに登録するのが正攻法。
他のケースで実例があるか引き続き確認中。

**Comment by bee7813993** [comment]
・私の考える本件の目的
ファイル名に曲名以外の情報があるのにファイル名のみをチェックして他のタイアップ曲として認識されてしまう場合、手動でデータベースを修正するという手間を省略したい

・解決手段
曲名以外の項目もチェックしてほしい

・解決案
案を書いておきます。（処理的に大変かもしれないけれど）
【現状】
曲名が同じものがある
↓
DBに情報がない  (yes) → ファイル名の情報を採用
↓ (no)
DBの情報をリストに適用

となっていると思うのですが、

【希望】
曲名が同じものがある
↓
DBに情報がない  (yes) → ファイル名の情報を採用
↓ (no)
ファイル名の曲名以外（タイアップ名、歌手名 とりあえずその2つでも）の情報と文字数の7割以上※一致する（ファイル名に情報がない項目はチェックしない）→ ファイル名の情報を採用
↓ (yes)
DBの情報をリストに適用

※このあたりの境目が要調整かと思います。文字一致率5割とタイアップ、歌手名がOR条件でも相当救えるかと思います

全体設定画面にこの機能のON/Offができるとしたら、おっしゃる通りユーザー側が「トータルでは無効化するほうが悪化する可能性が高い。」というようであれば、フォルダー単位で設定できるように動画制作者側が「フォルダー設定」の中にこの機能のOn/Offを設定できるようにして「YukaLister.config」にこの機能のOn/Offを設定できるかどうかを選択できるようにする、というのはどうでしょうか？

**Comment by shinta0806** [comment]
提案いただいた手法を Ver 6.40 にて対応完了しました。
